-- MySQL Script generated by MySQL Workbench
-- Fri Oct  5 19:30:51 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AllanTask
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AllanTask
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AllanTask` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `AllanTask` ;

-- -----------------------------------------------------
-- Table `AllanTask`.`at_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AllanTask`.`at_user` ;

CREATE TABLE IF NOT EXISTS `AllanTask`.`at_user` (
  `cod_user` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(250) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`cod_user`),
  UNIQUE INDEX `cod_user_UNIQUE` (`cod_user` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AllanTask`.`at_notas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AllanTask`.`at_notas` ;

CREATE TABLE IF NOT EXISTS `AllanTask`.`at_notas` (
  `id_notas` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `data` DATETIME NULL,
  `cod_user` INT NOT NULL,
  PRIMARY KEY (`id_notas`, `cod_user`),
  INDEX `fk_at_notas_at_user_idx` (`cod_user` ASC) VISIBLE,
  CONSTRAINT `fk_at_notas_at_user`
    FOREIGN KEY (`cod_user`)
    REFERENCES `AllanTask`.`at_user` (`cod_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
