-- MySQL Script generated by MySQL Workbench
-- Thu Sep 27 21:24:20 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AllanTask
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AllanTask
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AllanTask` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `AllanTask` ;

-- -----------------------------------------------------
-- Table `AllanTask`.`at_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AllanTask`.`at_user` ;

CREATE TABLE IF NOT EXISTS `AllanTask`.`at_user` (
  `cod_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`cod_user`),
  UNIQUE INDEX `cod_user_UNIQUE` (`cod_user` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AllanTask`.`at_notas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AllanTask`.`at_notas` ;

CREATE TABLE IF NOT EXISTS `AllanTask`.`at_notas` (
  `titulo` VARCHAR(20) NOT NULL,
  `Texto` VARCHAR(100) NULL,
  `data` DATETIME NULL,
  PRIMARY KEY (`titulo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
